### ISSUE TITLE
Mountain weight

### ISSUE THREAD

**Issue by koenkaan** [TerraForged/TerraForged#64] opened 2020-03-17 09:42 UTC
When changing the Mountain Weight, in world generation options, to zero Minecraft will stop functioning.

**Comment by dags-** [comment] 2020-03-17 10:19
What version are you using?

**Comment by koenkaan** [comment] 2020-03-17 11:51
0.0.3

**Comment by dags-** [comment] 2020-03-17 12:53
Thanks, found the cause of the issue. Will be fixed in the next update (0.0.5)

**Comment by JTandT** [comment] 2020-03-17 20:54
This bug also applies to Badlands and Volcanoes in addition to Mountains in 0.0.4

**Closed** 2020-03-18 19:39 UTC
Labels: bug
